<?php

namespace AppBundle\Repository;

/**
 * ProofRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProofRepository extends \Doctrine\ORM\EntityRepository
{
}
