<?php

namespace AppBundle\Repository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository
{

	public function findTasksByDay($familyId, $day, $page = 1)
	{
	    $q = $this
	        ->createQueryBuilder('t')
	        // ->where('DATE_FORMAT(t.start ,'%Y-%m-%d') = :day')
	        // ->andWhere('1') // User family
	        // ->setParameter('day', $day)
	        ->getQuery();

	    return $q->getResult();
	}
}
