<?php

namespace AppBundle\Repository;
use DateTime;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository
{

	public function findTasksByDay($familyId, $day, $page = 1)
	{
	    $q = $this
	        ->createQueryBuilder('t')
	        ->where('t.start = :day')
	        ->setParameter('day', new Datetime($day), \Doctrine\DBAL\Types\Type::DATETIME)
	        ->getQuery();

	    return $q->getResult();
	}
}
