# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
   	app.guid:
       	class: AppBundle\Service\Guid
    app.form.profile:
        class: FOSChildBundle\Form\Type\ProfileFormType
        tags:
            - { name: form.type, alias: app_user_profile }
